Repository fservant/GitAnalytics, pull requests merged in 2018-10, with the labels that each got.

#21 Access JSON file through javascript
  CI/Site/project/index.html
  CI/Site/project/js/script.js
Labels: CI

#22 Index file and Style
  .DS_Store
  CodeReview/index.html
  CodeReview/style.css
  README.md
Labels: CodeReview

#26 Bug Fixes
  deepHistory/src/app/repo/repo.component.ts
  deepHistory/src/app/user/user.component.ts
Labels: DH, bug

#28 Reformatted code to have pretty spacing
  CI/Site/public/project/js/script.js
Labels: CI

#27 Load from firebase
  CI/Site/public/project/js/script.js
Labels: CI
